### PR TITLE
Update go-textile and more granular wallet update callbacks

### PR DESCRIPTION
**Pull request by asutula**

### CODE REVIEW

**Review by sanderpick — APPROVED** [review]
Looks good! What are your thoughts on walking back the version to `0.1.x` style?

**Comment by asutula** [comment]
Yea we can do that. Cocoapods strongly encourages using semantic versioning (https://semver.org/), so we'll blast through 1.0 quickly even if we first release a 0.1.x version.

**Comment by sanderpick** [comment]
Cool, sounds good

**Comment by sanderpick** [comment]
Test test one two one two

**Pull request merged**
